pipeline {
    agent any

    environment {
        GITHUB_REPO = 'https://github.com/nttd-KrishnatHogale/PetStoreRestAssured.git'
        REPORTS_DIR = 'PetStoreRestAssuredProject/reports'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: "${env.GITHUB_REPO}", branch: 'main'
            }
        }

        stage('Build') {
            steps {
                dir('PetStoreRestAssuredProject') {
                    bat 'mvn clean test'
                }
            }
//             post {
//             always {
//             bat 'echo hello'}
//             }
        }
    }

//     post {
//         always {
//         script {
//                         dir("${env.REPORTS_DIR}") {
//                             bat 'echo "Currently working directory: %cd%"'
//                         }
//                     }
//             archiveArtifacts artifacts: "${env.REPORTS_DIR}/**", allowEmptyArchive: true
//         }
//     }

// post {
//         always {
//             script {
//                 // Print a custom message
//                 bat 'echo steps completed'
//
//                 // Archive the reports
// //                 archiveArtifacts artifacts: "${env.REPORTS_DIR}/**", allowEmptyArchive: true
//             }
//         }
//     }
}
