pipeline {
    agent any

    environment {
        GITHUB_REPO = 'https://github.com/nttd-KrishnatHogale/PetStoreRestAssured.git'
        REPORTS_DIR = 'PetStoreRestAssuredProject/reports'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: "${env.GITHUB_REPO}", branch: 'main'
            }
        }

        stage('Build') {
            steps {
                bat 'cd'
                dir('PetStoreRestAssuredProject') {
                    bat 'mvn clean test'
                }
            }
        }

        stage('Verify Reports Directory') {
            steps {
                dir('PetStoreRestAssuredProject/reports') {
                    bat 'echo Currently working directory: %cd%'
                }
            }
        }
    }

    post {
        always {
            dir('PetStoreRestAssuredProject/reports') {
                bat 'echo Currently working directory: %cd%'
            }
        }
    }
}
