pipeline {
    agent any

    environment {
        GITHUB_REPO = 'https://github.com/nttd-KrishnatHogale/PetStoreRestAssured.git'
        REPORTS_DIR = 'PetStoreRestAssuredProject/reports'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: "${env.GITHUB_REPO}", branch: 'main'
            }
        }

        stage('Build') {
            steps {
                dir('PetStoreRestAssuredProject') {
                    bat 'mvn clean test'
                }
            }
        }

        stage('Verify Reports Directory') {
            steps {
                dir("${env.REPORTS_DIR}") {
                    echo "Currently working directory: %cd%"
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: "${env.REPORTS_DIR}/**", allowEmptyArchive: true
        }
    }
}
